apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: image-classification-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-classification-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_20s
        target:
          type: AverageValue
          averageValue: "20"
