apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: default
data:
  config.yaml: |
    rules:
      default: false
      custom:
        - seriesQuery: 'http_requests_total{service="dispatcher-service"}'
          resources:
            overrides:
              namespace: { resource: "namespace" }
              pod: { resource: "pod" }
          name:
            as: "http_requests_per_20s"
          metricsQuery: 'sum(rate(http_requests_total{service="dispatcher-service"}[20s])) by (pod)'
