apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classification-server
  template:
    metadata:
      labels:
        app: image-classification-server
    spec:
      containers:
        - name: image-classification-server
          image: arslan199319457/image-classification-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 3
