apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  labels:
    app: image-classification-server 
spec:
  selector:
    app: image-classification-server
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
  type: NodePort
